name = "da-content"
main = "src/index.js"
compatibility_date = "2023-11-21"

services = [
  { binding = "daadmin", service = "da-admin" }
]

[env.stage]
services = [
  { binding = "daadmin", service = "da-admin" }
]